[package]
name = "dojo-abigen"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
cainome.workspace = true
camino.workspace = true
scarb.workspace = true
serde.workspace = true
