[package]
cairo-version = "=2.8.4"
edition = "2024_07"
description = "The Dojo Core library for autonomous worlds."
name = "dojo"
version = "1.0.0-rc.0"

[dependencies]
starknet = "=2.8.4"
dojo_plugin = { git = "https://github.com/dojoengine/dojo", branch = "feat/dojo-1-rc0" }

[dev-dependencies]
cairo_test = "=2.8.4"

[lib]

[[target.starknet-contract]]
sierra = true
