kind = "ModelManifest"
class_hash = "0x3ced4e81be768d209393d1d147137209c6bb4a1ad32cea4c5da0aac8181d51b"
qualified_path = "dojo_simple::models::position"
tag = "DEFAULT_NAMESPACE-Position"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false
