kind = "DojoModel"
class_hash = "0x5669a4762502c857fd972cadd18d718ca0d1ae26932f066e1afaee5a61e2f5f"
qualified_path = "dojo_simple::actions::model_in_contract"
tag = "DEFAULT_NAMESPACE-ModelInContract"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "a"
type = "u8"
key = false
