name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.80.0

jobs:
  test:
    runs-on: ubuntu-latest-4-cores
    container:
      image: ghcr.io/dojoengine/dojo-core-dev:5995840
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: |
          scripts/tests.sh

  cairofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.7.1"
      - run: |
          bash scripts/cairo_fmt.sh --check

  rustfmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/dojo-core-dev:5995840
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: scripts/rust_fmt.sh --check

  docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/dojo-core-dev:5995840
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: >
          scripts/docs.sh
